# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Flutter SDK
        # You may pin to the exact commit or the version.
        # uses: MobileDevOps/flutter-sdk-action@a93694305106b954a8b85195ab7cd4bfec0401bf
        uses: MobileDevOps/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.3.10
            # The Flutter SDK Version
      - name: build
        run: |
          ls -l
          flutter build apk

      - name: upload apk to release
        uses: actions/upload-artifact@master
        with: 
          name: apk_release
          path: ${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            ${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk
