# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter SDK
        # You may pin to the exact commit or the version.
        # uses: MobileDevOps/flutter-sdk-action@a93694305106b954a8b85195ab7cd4bfec0401bf
        uses: MobileDevOps/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.3.10
            # The Flutter SDK Version
      - name: clone repo
        run: |
          git clone https://github.com/bilibili10633/tieba_flutter.git .
          ls -l
      - name: build
        run: |
          ls -l
          flutter build apk
